version: '3.1'

services:
  adotestability-sql:
    image: adotestability-sql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11433:1433"
    secrets:
      - sql-eula.txt
    
secrets:
  sql-eula.txt:
    file: ./sql-eula.txt